http: add missing header bootlegged by boost < 1.72
httpserver.cpp:74:10: error: no template named 'deque' in namespace 'std'
    std::deque<std::unique_ptr<WorkItem>> queue;
    ~~~~~^

Github-Pull: #17249
Rebased-From: a5929130223973636f3fd25fbfaf2953f2ec96a9
Tree-SHA512: 47ca773676a3f181bb265af30df6ca83669ffbb2dc79ce7c1ffd6f2d110df8406c2f73daddbcb1c038661472a1be93f46e9d3b8c3d2f33fe484f5774070e59ae